export interface Company {
  id: string;
  name: string;
  ghostScore: number;
  logo: string;
}

export interface JobPosting {
  id: string;
  title: string;
  companyId: string;
  location: string;
  salaryMin: number;
  salaryMax: number;
  techStack: string[];
  daysPosted: number;
  ghostScore: number;
  redFlags: string[];
  greenFlags: string[];
}

export const companies: Company[] = [
  { id: "co-1", name: "Stripe", ghostScore: 8, logo: "/logos/stripe.svg" },
  { id: "co-2", name: "Vercel", ghostScore: 9, logo: "/logos/vercel.svg" },
  { id: "co-3", name: "Linear", ghostScore: 9, logo: "/logos/linear.svg" },
  { id: "co-4", name: "Notion", ghostScore: 7, logo: "/logos/notion.svg" },
  { id: "co-5", name: "Figma", ghostScore: 8, logo: "/logos/figma.svg" },
  { id: "co-6", name: "Retool", ghostScore: 6, logo: "/logos/retool.svg" },
  { id: "co-7", name: "Brex", ghostScore: 6, logo: "/logos/brex.svg" },
  { id: "co-8", name: "Mercury", ghostScore: 7, logo: "/logos/mercury.svg" },
  { id: "co-9", name: "Ramp", ghostScore: 5, logo: "/logos/ramp.svg" },
  { id: "co-10", name: "Lattice", ghostScore: 5, logo: "/logos/lattice.svg" },
  { id: "co-11", name: "Airtable", ghostScore: 6, logo: "/logos/airtable.svg" },
  { id: "co-12", name: "Loom", ghostScore: 7, logo: "/logos/loom.svg" },
  { id: "co-13", name: "Neon", ghostScore: 3, logo: "/logos/neon.svg" },
  { id: "co-14", name: "TechVentures Inc", ghostScore: 2, logo: "/logos/techventures.svg" },
  { id: "co-15", name: "CloudScale Systems", ghostScore: 3, logo: "/logos/cloudscale.svg" },
  { id: "co-16", name: "DataFlow Analytics", ghostScore: 4, logo: "/logos/dataflow.svg" },
  { id: "co-17", name: "Sourcegraph", ghostScore: 8, logo: "/logos/sourcegraph.svg" },
  { id: "co-18", name: "Supabase", ghostScore: 8, logo: "/logos/supabase.svg" },
];

export const jobPostings: JobPosting[] = [
  // High ghost score (8-9) — trustworthy
  {
    id: "job-1",
    title: "Senior Full Stack Engineer",
    companyId: "co-1",
    location: "San Francisco, CA (Remote)",
    salaryMin: 180000,
    salaryMax: 250000,
    techStack: ["TypeScript", "React", "Node.js", "PostgreSQL", "Redis"],
    daysPosted: 3,
    ghostScore: 9,
    redFlags: [],
    greenFlags: ["Clear salary range in posting", "Fast response reported", "Transparent hiring process"],
  },
  {
    id: "job-2",
    title: "Frontend Engineer",
    companyId: "co-2",
    location: "Remote",
    salaryMin: 160000,
    salaryMax: 220000,
    techStack: ["Next.js", "React", "TypeScript", "Vercel"],
    daysPosted: 5,
    ghostScore: 9,
    redFlags: [],
    greenFlags: ["Remote-first culture", "Open source friendly", "Quick interview feedback"],
  },
  {
    id: "job-3",
    title: "Backend Engineer",
    companyId: "co-3",
    location: "Remote (US)",
    salaryMin: 170000,
    salaryMax: 230000,
    techStack: ["Go", "TypeScript", "PostgreSQL", "GraphQL"],
    daysPosted: 2,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Small team, direct contact", "No ghosting reports", "Clear job description"],
  },
  {
    id: "job-4",
    title: "Software Engineer - Platform",
    companyId: "co-4",
    location: "New York, NY / Remote",
    salaryMin: 165000,
    salaryMax: 225000,
    techStack: ["TypeScript", "React", "Python", "AWS"],
    daysPosted: 7,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Competitive benefits", "Structured interview process", "Timely updates"],
  },
  {
    id: "job-5",
    title: "Staff Engineer - Infrastructure",
    companyId: "co-5",
    location: "San Francisco or Remote",
    salaryMin: 220000,
    salaryMax: 300000,
    techStack: ["Rust", "Go", "Kubernetes", "Terraform"],
    daysPosted: 4,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Senior role, serious hiring", "Good Glassdoor reviews", "Explicit salary band"],
  },
  {
    id: "job-6",
    title: "Full Stack Developer",
    companyId: "co-17",
    location: "Remote",
    salaryMin: 155000,
    salaryMax: 205000,
    techStack: ["Go", "TypeScript", "React", "PostgreSQL"],
    daysPosted: 6,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Developer tools company", "Transparent communication", "Respectful rejection feedback"],
  },
  {
    id: "job-7",
    title: "Backend Engineer - Database",
    companyId: "co-18",
    location: "Remote (Global)",
    salaryMin: 150000,
    salaryMax: 200000,
    techStack: ["TypeScript", "PostgreSQL", "Go", "Kubernetes"],
    daysPosted: 1,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Open source company", "Active community", "Clear role expectations"],
  },
  // Medium ghost score (5-6)
  {
    id: "job-8",
    title: "Senior React Developer",
    companyId: "co-6",
    location: "San Francisco, CA",
    salaryMin: 160000,
    salaryMax: 200000,
    techStack: ["React", "TypeScript", "Node.js", "GraphQL"],
    daysPosted: 12,
    ghostScore: 6,
    redFlags: ["Posting has been up for 2+ weeks"],
    greenFlags: ["Known product", "Reasonable tech stack"],
  },
  {
    id: "job-9",
    title: "Software Engineer",
    companyId: "co-7",
    location: "New York / Remote",
    salaryMin: 170000,
    salaryMax: 230000,
    techStack: ["Python", "React", "AWS", "PostgreSQL"],
    daysPosted: 8,
    ghostScore: 6,
    redFlags: ["Salary not listed initially"],
    greenFlags: ["Fintech, well-funded", "Structured rounds"],
  },
  {
    id: "job-10",
    title: "Full Stack Engineer",
    companyId: "co-8",
    location: "Remote",
    salaryMin: 155000,
    salaryMax: 195000,
    techStack: ["Ruby on Rails", "React", "PostgreSQL"],
    daysPosted: 10,
    ghostScore: 5,
    redFlags: ["Some delayed response reports"],
    greenFlags: ["Banking/fintech", "Clear job level"],
  },
  {
    id: "job-11",
    title: "Backend Engineer",
    companyId: "co-9",
    location: "New York, NY",
    salaryMin: 165000,
    salaryMax: 215000,
    techStack: ["Go", "Python", "Kafka", "PostgreSQL"],
    daysPosted: 14,
    ghostScore: 5,
    redFlags: ["Role reposted multiple times", "Vague 'competitive salary'"],
    greenFlags: ["Growing company", "Modern stack"],
  },
  {
    id: "job-12",
    title: "Frontend Engineer",
    companyId: "co-10",
    location: "San Francisco / Remote",
    salaryMin: 150000,
    salaryMax: 190000,
    techStack: ["React", "TypeScript", "Redux", "Jest"],
    daysPosted: 9,
    ghostScore: 5,
    redFlags: ["Slow follow-up in some cases"],
    greenFlags: ["HR tech, stable", "Defined process"],
  },
  {
    id: "job-13",
    title: "Software Engineer - Platform",
    companyId: "co-11",
    location: "San Francisco, CA",
    salaryMin: 175000,
    salaryMax: 235000,
    techStack: ["JavaScript", "React", "Node.js", "AWS"],
    daysPosted: 11,
    ghostScore: 6,
    redFlags: ["Large applicant pool"],
    greenFlags: ["Household name product", "Good benefits"],
  },
  {
    id: "job-14",
    title: "Senior Software Engineer",
    companyId: "co-12",
    location: "Remote (US)",
    salaryMin: 165000,
    salaryMax: 220000,
    techStack: ["TypeScript", "React", "Node.js", "WebRTC"],
    daysPosted: 6,
    ghostScore: 6,
    redFlags: [],
    greenFlags: ["Async video product", "Remote-first"],
  },
  {
    id: "job-15",
    title: "DevOps Engineer",
    companyId: "co-16",
    location: "Austin, TX / Remote",
    salaryMin: 140000,
    salaryMax: 180000,
    techStack: ["Kubernetes", "Terraform", "Python", "GCP"],
    daysPosted: 15,
    ghostScore: 5,
    redFlags: ["Generic job description", "No salary range"],
    greenFlags: ["Analytics domain", "Modern infra"],
  },
  // Low ghost score (2-3) — risky
  {
    id: "job-16",
    title: "Full Stack Developer - Urgent",
    companyId: "co-13",
    location: "Remote",
    salaryMin: 90000,
    salaryMax: 120000,
    techStack: ["React", "Node.js", "PostgreSQL"],
    daysPosted: 45,
    ghostScore: 3,
    redFlags: ["Listing up 45+ days", "Urgent in title", "Low salary for 'Senior'", "No response to many applicants"],
    greenFlags: [],
  },
  {
    id: "job-17",
    title: "Senior Software Engineer",
    companyId: "co-14",
    location: "Mountain View, CA",
    salaryMin: 0,
    salaryMax: 0,
    techStack: ["Java", "Spring", "AWS", "Kafka"],
    daysPosted: 60,
    ghostScore: 2,
    redFlags: ["No salary disclosed", "Posting 60+ days", "Company hard to verify", "Multiple ghosting reports"],
    greenFlags: [],
  },
  {
    id: "job-18",
    title: "React Developer",
    companyId: "co-14",
    location: "Remote - US",
    salaryMin: 80000,
    salaryMax: 100000,
    techStack: ["React", "JavaScript", "REST APIs"],
    daysPosted: 30,
    ghostScore: 2,
    redFlags: ["Vague company info", "Below market salary", "Applicants report no reply"],
    greenFlags: [],
  },
  {
    id: "job-19",
    title: "Backend Developer",
    companyId: "co-15",
    location: "Denver, CO",
    salaryMin: 95000,
    salaryMax: 130000,
    techStack: ["Python", "Django", "PostgreSQL", "Docker"],
    daysPosted: 25,
    ghostScore: 3,
    redFlags: ["Role reposted 3x", "Interview no-shows reported", "Unclear team size"],
    greenFlags: ["Location specified"],
  },
  {
    id: "job-20",
    title: "Full Stack Engineer",
    companyId: "co-15",
    location: "Chicago, IL / Hybrid",
    salaryMin: 100000,
    salaryMax: 140000,
    techStack: ["TypeScript", "React", "Node.js", "MongoDB"],
    daysPosted: 20,
    ghostScore: 3,
    redFlags: ["Delayed or no feedback", "Changing requirements in JD"],
    greenFlags: ["Hybrid option"],
  },
  {
    id: "job-21",
    title: "Software Development Engineer",
    companyId: "co-16",
    location: "Seattle, WA",
    salaryMin: 0,
    salaryMax: 0,
    techStack: ["Java", "Spark", "Kafka", "AWS"],
    daysPosted: 40,
    ghostScore: 4,
    redFlags: ["Salary not listed", "Very long posting age", "Generic JD"],
    greenFlags: ["Big data stack"],
  },
  // More mix of scores
  {
    id: "job-22",
    title: "Staff Frontend Engineer",
    companyId: "co-1",
    location: "Remote",
    salaryMin: 200000,
    salaryMax: 280000,
    techStack: ["TypeScript", "React", "GraphQL", "Jest"],
    daysPosted: 4,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Staff level clarity", "Strong eng culture", "Transparent comp"],
  },
  {
    id: "job-23",
    title: "Platform Engineer",
    companyId: "co-2",
    location: "Remote",
    salaryMin: 170000,
    salaryMax: 240000,
    techStack: ["Go", "Kubernetes", "Terraform", "Prometheus"],
    daysPosted: 2,
    ghostScore: 9,
    redFlags: [],
    greenFlags: ["Infra focus", "Fast hiring", "Clear leveling"],
  },
  {
    id: "job-24",
    title: "Junior Full Stack Developer",
    companyId: "co-4",
    location: "New York, NY",
    salaryMin: 120000,
    salaryMax: 155000,
    techStack: ["JavaScript", "React", "Node.js", "SQL"],
    daysPosted: 9,
    ghostScore: 7,
    redFlags: [],
    greenFlags: ["Junior-friendly", "Mentorship mentioned", "Salary range"],
  },
  {
    id: "job-25",
    title: "Senior Backend Engineer",
    companyId: "co-6",
    location: "San Francisco",
    salaryMin: 175000,
    salaryMax: 225000,
    techStack: ["TypeScript", "PostgreSQL", "Redis", "Event-driven"],
    daysPosted: 13,
    ghostScore: 5,
    redFlags: ["Some candidates never heard back"],
    greenFlags: ["Internal tools space", "Interesting problems"],
  },
  {
    id: "job-26",
    title: "Mobile Engineer (React Native)",
    companyId: "co-5",
    location: "Remote",
    salaryMin: 160000,
    salaryMax: 210000,
    techStack: ["React Native", "TypeScript", "iOS", "Android"],
    daysPosted: 5,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Design-focused company", "Clear scope", "Good reviews"],
  },
  {
    id: "job-27",
    title: "Site Reliability Engineer",
    companyId: "co-7",
    location: "New York / Remote",
    salaryMin: 180000,
    salaryMax: 240000,
    techStack: ["Go", "Kubernetes", "Datadog", "Terraform"],
    daysPosted: 7,
    ghostScore: 6,
    redFlags: ["Process can be slow"],
    greenFlags: ["SRE dedicated role", "On-call clarity"],
  },
  {
    id: "job-28",
    title: "Full Stack Engineer - Growth",
    companyId: "co-3",
    location: "Remote",
    salaryMin: 165000,
    salaryMax: 220000,
    techStack: ["TypeScript", "React", "PostgreSQL", "Analytics"],
    daysPosted: 1,
    ghostScore: 9,
    redFlags: [],
    greenFlags: ["New role", "Growth team", "Async culture"],
  },
  {
    id: "job-29",
    title: "Software Engineer II",
    companyId: "co-11",
    location: "San Francisco",
    salaryMin: 168000,
    salaryMax: 228000,
    techStack: ["Python", "React", "Django", "AWS"],
    daysPosted: 14,
    ghostScore: 5,
    redFlags: ["High volume hiring", "Variable response time"],
    greenFlags: ["Level specified", "Known brand"],
  },
  {
    id: "job-30",
    title: "Principal Engineer",
    companyId: "co-18",
    location: "Remote (Global)",
    salaryMin: 220000,
    salaryMax: 300000,
    techStack: ["Go", "PostgreSQL", "Kubernetes", "Open Source"],
    daysPosted: 3,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Principal track", "OSS contribution", "Strong eng team"],
  },
  {
    id: "job-31",
    title: "Frontend Engineer - Design Systems",
    companyId: "co-5",
    location: "San Francisco or Remote",
    salaryMin: 170000,
    salaryMax: 230000,
    techStack: ["TypeScript", "React", "Storybook", "Figma"],
    daysPosted: 6,
    ghostScore: 8,
    redFlags: [],
    greenFlags: ["Design systems team", "Figma integration", "Inclusive process"],
  },
  {
    id: "job-32",
    title: "Backend Engineer - Payments",
    companyId: "co-1",
    location: "Seattle / Remote",
    salaryMin: 185000,
    salaryMax: 255000,
    techStack: ["Ruby", "Go", "PostgreSQL", "Kafka"],
    daysPosted: 2,
    ghostScore: 9,
    redFlags: [],
    greenFlags: ["Payments domain", "Clear seniority", "Strong feedback culture"],
  },
  {
    id: "job-33",
    title: "Solutions Engineer",
    companyId: "co-13",
    location: "Remote",
    salaryMin: 110000,
    salaryMax: 145000,
    techStack: ["SQL", "Python", "JavaScript", "APIs"],
    daysPosted: 22,
    ghostScore: 3,
    redFlags: ["Many applicants ghosted", "Unclear hiring timeline"],
    greenFlags: ["Solutions focus", "Remote"],
  },
  {
    id: "job-34",
    title: "Senior DevOps Engineer",
    companyId: "co-14",
    location: "Remote - USA",
    salaryMin: 0,
    salaryMax: 0,
    techStack: ["AWS", "Terraform", "Jenkins", "Python"],
    daysPosted: 55,
    ghostScore: 2,
    redFlags: ["No salary", "Old posting", "Fake or stale listing suspected"],
    greenFlags: [],
  },
  {
    id: "job-35",
    title: "Engineering Manager",
    companyId: "co-8",
    location: "Remote",
    salaryMin: 190000,
    salaryMax: 250000,
    techStack: ["Leadership", "TypeScript", "React", "PostgreSQL"],
    daysPosted: 8,
    ghostScore: 7,
    redFlags: [],
    greenFlags: ["EM role", "Fintech", "Team growth stage"],
  },
];

export function nameToSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

export function getCompanyBySlug(slug: string): (typeof companies)[number] | undefined {
  return companies.find((c) => nameToSlug(c.name) === slug);
}

export function getJobsByCompanyId(companyId: string): JobPosting[] {
  return jobPostings.filter((j) => j.companyId === companyId);
}

export function getJobById(id: string): JobPosting | undefined {
  return jobPostings.find((j) => j.id === id);
}

export function getJobsByIds(ids: string[]): JobPosting[] {
  const set = new Set(ids);
  return jobPostings.filter((j) => set.has(j.id));
}
